#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <number_of_nodes>"
  exit 1
fi

NUM_NODES=$1
FILENAME="cluster.yaml" 

cat <<EOF > "$FILENAME"
# YAML is generated by generate-kind-nodes.sh
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
EOF

for ((i=1; i<=$NUM_NODES; i++)); do
  if [ $i -eq 1 ]; then
    ROLE="control-plane"
  else
    ROLE="worker"
  fi
  echo "  - role: $ROLE" >> "$FILENAME"
done

echo "YAML file '$FILENAME' created with $NUM_NODES nodes."
